### ISSUE TITLE
There is some problem while sending message to WhatsApp.

### ISSUE THREAD

**Issue by KoolPal** [naranarethiya/whatsapp-web-interaction-suite#1]
Hi,

Thanks for this awesome extension.

Just noticed since some time that I keep getting this message.

There is some problem while sending message to WhatsApp.

I tried different browsers too

![image](https://github.com/user-attachments/assets/8dec3a8b-57bf-48c7-8951-b31dca778949)

Please check and guide.

**Comment by naranarethiya** [comment]
Hello @KoolPal,

Can you please provide the console log of web.whatsapp.com?

**Comment by KoolPal** [comment]
@naranarethiya Thanks a lot for responding.

Looks like it was a temporary issue at that time. Seems sorted now. I will reopen this if I encounter it again and provide console logs as well.

Once again, thanks a lot for this awesome extension. Really appreciate this from you!

**Comment by naranarethiya** [comment]
@KoolPal  Thanks for using the extension! Please feel free to reach out if you encounter any issues or have feature requests. I'll do my best to address and implement them.
