### ISSUE TITLE
Request - send a carousel template on whatsapp

### ISSUE THREAD

**Issue by KoolPal** [naranarethiya/whatsapp-web-interaction-suite#2]
Hi there!

This is a request. Using your extension is there ANY way we can send a carousel template on whatsapp?

This page has a lot of information which you may find useful.
https://support.exotel.com/support/solutions/articles/3000124852-how-to-create-and-send-a-carousel-template-on-whatsapp

Thanks a lot!

**Comment by naranarethiya** [comment]
I don't think that is possible as it's whatsapp business feature.
Behind the scen this extension uses [wweb.js](https://wwebjs.dev/) so we can add following feature in extension but this carousel one.

https://github.com/pedroslopez/whatsapp-web.js?tab=readme-ov-file#supported-features

**Comment by KoolPal** [comment]
@naranarethiya Thanks a lot for letting me know. 
Please do not mind me. We are a small family owned business with NO TECH TEAM 
I manage what I can via stackoverflow and chatgpt, claude, etc 😁
Sorry to bother you on this.
Please do not mind future messages like these in case I have some 'basic' queries
Thanks a lot

**Comment by naranarethiya** [comment]
@KoolPal
I am gald that you have requested a feature but this one not seems possible and I will be happy to receive such future requests.
