### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tahiriqbalnajam** [naranarethiya/whatsapp-web-interaction-suite#4]
Hi,
1. There is no space in number
2. I have already logged to my WhatsApp web

I am trying to first deploy on my local host, but no response, kindly check the screenshot for console errors.

![image](https://github.com/user-attachments/assets/68babb09-8df8-4b1d-97e7-fa8b1df8efd4)

**Comment by narethiya-godaddy** [comment]
@tahiriqbalnajam Can you share the code that you are trying ?

**Comment by tahiriqbalnajam** [comment]
Here it is, which I just put in a simple HTML file,
I also tried in Vue template after installing "WhatsApp Web".
`<form id="whatsapp-form">
        <label for="phone-number">Phone Number:</label>
        <input type="text" id="phone-number" name="phone-number" required>
        <br><br>
        <label for="message">Message:</label>
        <textarea id="message" name="message" required></textarea>
        <br><br>
        <button type="submit">Send Message</button>
    </form>

    <script>
        document.getElementById('whatsapp-form').addEventListener('submit', function(event) {
            alert('Form submitted');
            event.preventDefault();

            const phoneNumber = document.getElementById('phone-number').value;
            const message = document.getElementById('message').value;

           // Send text message
            window.whatsappWebSuite.sendTextMessage(
                '00923217050405', 
                'test message'
            );

            document.addEventListener('whatsappSendResponse', function(e, data) {
                if(e.detail.success) {
                    alert('Message sent successfully!');
                }
                else {
                    // handle fail
                    alert('Failed to send message.');
                }
            })
        });
    </script>`

**Comment by narethiya-godaddy** [comment]
Why you are adding `00` in mobile number at start?

**Comment by narethiya-godaddy** [comment]
i have run your code in here and its working fine for me, try to use `923217050405` as mobile number and try
@tahiriqbalnajam

**Comment by naranarethiya** [comment]
Why you are prepanding `00` in mobile number? Can you try `923217050405 ` with this?
@tahiriqbalnajam

**Comment by tahiriqbalnajam** [comment]
Thank you.
